--- #YAML:1.0
name: PPI-Metric-Basic
version: 0.28
author:
  - Leon Brocard <acme@astray.com>
abstract: Provide basic software metrics
license: perl
requires:
  PPI: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
provides:
  PPI::Metric::Basic:
    file: lib/PPI/Metric/Basic.pm
    version: 0.28
generated_by: Module::Build version 0.25
